dist: trusty
language: java
jdk:
  - oraclejdk8
notifications:
  email:
    recipients:
      - cibuilds@duracloud.org
    on_success: change
    on_failure: always
  slack: lyrasis:ctcQAEKjVcDFe9bTyMfH6PtI
before_install:
  - sudo apt-get -qq update
install:
  - mvn install -DskipTests --batch-mode
script:
  - mvn test -DskipIntTests
sudo: true
